### PR TITLE
On date change, grab snapshot of showing orbital paths

### PR DESCRIPTION
**Pull request by samadd**
We listen for the input date change, and grab a snapshot of all orbital paths that are set to show, and then use that when the data comes in in the same way that orbital paths are shown if the query string is set to contain satellite ids.

### CODE REVIEW

**Comment by HP4k1h5** [comment]
Thanks, Sam for looking into this. It works well when one satellite is clicked. im able to go back/forth through time and the satellite orbit remains highlighted. However, when more than one satellite orbit is shown, going back/forth in time causes essentially everything to disappear. have you seen this behavior?

looking over the code, and doing some debugging, i haven't found the source of this behavior

**Comment by samadd** [comment]
@HP4k1h5 - thanks. This is very odd behaviour indeed. I've been looking at it this evening, but yet to figure out why having more than one highlighted entity would break things! Even stranger, if I go from 6th August to 1st with 2+ entities selected, then nothing else shows except for when I scroll the timeline back to the 6th, and magically they show up again...

I've a few more ideas to explore on the basis of what I've seen tonight, so should have it fixed soon!

**Comment by HP4k1h5** [comment]
@samadd very grateful for your work on this. i also noticed some of the quirks you're describing. i'll look into it further in a bit also.

**Comment by samadd** [comment]
The strangeness continues... on this branch, what seems to be happening is that when changing date, I see only a handful of satellites on the newly selected date, but if I move the date slider back to the previously selected date, then all the satellites re-appear. So today's date selected, select a few days back, then move back towards today's date. This seems to be independent of whether I've got anything selected or not, but I think is the cause of the behaviour observed. The main branch is working fine, so I'm going to start from there and see how it functions with the latest changes in main.

**Comment by samadd** [comment]
I think I've *finally* fixed(?) it... It seemed to be something to do with references to entities still remaining in the component that had been removed from the entity collection. So highlightedEntities, for example, might refer to entites that should be gone after viewer.entities.removeAll() gets called, and somehow when there are more than one(?) Cesium silently breaks, leaving no trace of an error.
So to fix this I've resorted to clobbering everything after first grabbing a list of any entities with showing paths (which I seemingly have to use the internal _value property to get the boolean inside the Cesium wrapper class).

**Comment by HP4k1h5** [comment]
@samadd Thank you for sorting this. I've noticed a number of buggy interactions have been cleaned up by these changes. Really nice work!

**Review by HP4k1h5 — APPROVED** [review]
🥳

**Pull request merged**
